// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace NetflixMoviesML.Model
{
    public class ModelInput
    {
        [ColumnName("show_id"), LoadColumn(0)]
        public string Show_id { get; set; }


        [ColumnName("type"), LoadColumn(1)]
        public string Type { get; set; }


        [ColumnName("title"), LoadColumn(2)]
        public string Title { get; set; }


        [ColumnName("director"), LoadColumn(3)]
        public string Director { get; set; }


        [ColumnName("cast"), LoadColumn(4)]
        public string Cast { get; set; }


        [ColumnName("country"), LoadColumn(5)]
        public string Country { get; set; }


        [ColumnName("date_added"), LoadColumn(6)]
        public string Date_added { get; set; }


        [ColumnName("release_year"), LoadColumn(7)]
        public float Release_year { get; set; }


        [ColumnName("rating"), LoadColumn(8)]
        public string Rating { get; set; }


        [ColumnName("duration"), LoadColumn(9)]
        public string Duration { get; set; }


        [ColumnName("listed_in"), LoadColumn(10)]
        public string Listed_in { get; set; }


        [ColumnName("description"), LoadColumn(11)]
        public string Description { get; set; }


    }
}
